import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { type ReactNode } from "react";
import { cookieToInitialState } from "wagmi";
import { ConnectButton } from "@rainbow-me/rainbowkit";

import { getConfig } from "../wagmi";
import { Providers } from "./providers";
import Sidebar from "./ui/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Wagmi",
  description: "Generated by create-wagmi",
};

export default function RootLayout(props: { children: ReactNode }) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie")
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <Sidebar>
            <div className="absolute top-4 right-4">
              <ConnectButton />
            </div>
            {props.children}
          </Sidebar>
        </Providers>
      </body>
    </html>
  );
}
